package com.ihcl.cart.utils

const val CLIENT_UNAVAILABLE_ERR_MSG="client is unavailable"
const val SOMETHING_WENT_WRONG_ERR_MSG="Something went wrong"
const val SERIALIZE_ERR_MSG="Unable to serialize client response"
const val INVALID_REQUEST_STRUCTURE_ERR_MSG="Invalid request structure"
const val NOT_ENOUGH_INVENTORY_ERR_MSG = "Not enough product available"
const val CUSTOMERHASH_REQUIRED_ERR_MSG = "CustomerHash is required"
const val CART_NOT_FOUND_ERR_MSG = "Cart Not Found"
const val ORDER_NOT_YET_PLACED_ERR_MSG = "Order not yet placed, please try after confirm"
const val ORDER_NOT_FOUND_ERR_MSG = "Order not found"
const val TOTAL_PAYABLE_AMOUNT_ZERO = "Total Payable Amount is 0.0 so, you can not apply any Tender Mode"
const val CART_ID_WITH_ROOMID_NOT_MATCHED_ERR_MSG = "CART ID with ROOM ID Not Matched"
const val CART_ID_WITH_ROOM_NUMBER_NOT_MATCHED_ERR_MSG = "CART ID with ROOM Number Not Matched"
const val PROVIDE_VALID_TENDER_MODE = "Please provide a valid tender mode, Tender mode not found"
const val UPDATE_ORDER_ERR_MSG = "order not yet updated, please try once or fetch the order and check order details"
const val ADD_TENDER_MODE_ERR_MSG = "you have chosen pay at hotel, can not add tender modes"
const val CARD_NUMBER_NOT_FOUND = " is not found"
const val RATE_CODE_NOT_FOUND = "Room is not available, Rate code not found"
const val SAME_GIFT_CARD_ERROR_MSG="Already used please use different Gift Card"
const val SUCCESS_STATUS_CODE= 200
const val BAD_REQUEST_STATUS_CODE= 400
const val HOTEL_ADDRESS_FORMAT_ERR_MSG= "Hotel address is a string, not contain special characters"
const val INVALID_JOURNEY_TYPE = "provide valid journey type"
const val INVALID_DETAILS = "Please provide valid details"
const val DUPLICATE_CART = "cart already exists"
const val BANK_NAME_NOT_FOUND = "Please provide bank name"
const val GUEST_CART_NOT_FOUND = "Guest cart not found"
const val ERROR_MESSAGE_FORMAT = "error {} "
const val INSUFFICIENT_OFFER_DETAILS = "offer code or name is missing"
const val VOUCHER_DETAILS_ERR_MSG = "Voucher details are mandatory"

